# -*- coding: utf-8 -*-
"""elanco.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tLwFJBdBk-wv7xI_btOshhY_t62dXDCA
"""

import pandas as pd

url = "https://raw.githubusercontent.com/elanco-python/szkolenie/main/extras/f500.csv"
df = pd.read_csv(url)

#df

#df.columns

url = "https://raw.githubusercontent.com/elanco-python/szkolenie/main/extras/f500.csv"
df = pd.read_csv(url, usecols=["profits","rank","company"] )
#df

#df.dtypes

df[ df["rank"]<=10 ]

df[df.profits>=1000]

df_result = df[ (df["profits"]>=1000) & (df["rank"]<=50) ]

#df_result

df_result.query(" rank<=50 and profits>=1000 ")

url = "https://raw.githubusercontent.com/elanco-python/szkolenie/main/extras/nba.csv"
df = pd.read_csv(url)
#df

df.dtypes

df["Weight"] /= 2

df

df["Height"]

df.dropna(axis=0, how="all", inplace=True)

def feet_2_cm(s):
  feet, inches = s.split("-")
  return int(feet)*30.2 + int(inches)*2.54

df["Height"] = df["Height"].apply(feet_2_cm)

df[ ["Name","Age","Salary"] ]

df_result = df.sort_values(["Salary", "Age"], ascending=[False, True])

df_result.to_csv("nba-sort.csv", sep="@", index=False)

url = "https://github.com/elanco-python/szkolenie/raw/main/extras/films.xlsx"
df = pd.read_excel(url, sheet_name=None)

df.keys()

df["SCI-FI AND FANTASY"]

